### ISSUE TITLE
Missing Javadoc

### ISSUE THREAD

**Issue by CoolKangaroo2022** [twitch4j/twitch4j#421]
Hello! I find in your [Developer Guidelines](https://twitch4j.github.io/docs/contribution/code-documentation/) that discuss rules on writing Javadoc.

However, I still witness some public classes without Javadocs, e.g.,
* common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
* rest-helix/src/main/java/com/github/twitch4j/helix/webhooks/topics/TwitchWebhookTopic.java
* rest-tmi/src/main/java/com/github/twitch4j/tmi/domain/Chatters.java
......

Would you like to add Javadoc for these classes, or they are just not that important?
If there is anything I can help with?

**Comment by PhilippHeuer** [comment]
Hi @CoolKangaroo2022,

since you have opened a lot of similar issues across different project and didn't respond/follow up in any of them we will be closing this as it looks like spam.
If you'r still interested in contributing, feel free to join us on our discord (linked in the readme) so we can talk about possible options on how you could contribute.

Best Regards
